# Generated by Django 4.2.7 on 2026-04-29 11:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SCHEDULED", "Scheduled"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("NO_SHOW", "No Show"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "reason_for_visit",
                    models.TextField(help_text="Reason for the appointment"),
                ),
                (
                    "symptoms",
                    models.TextField(
                        blank=True, help_text="Describe symptoms or concerns", null=True
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True, help_text="Relevant medical history", null=True
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes for the appointment",
                        null=True,
                    ),
                ),
                ("is_first_visit", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointments",
                        to="doctors.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "appointments_appointment",
                "ordering": ["-appointment_date", "-time_slot__start_time"],
                "unique_together": {("doctor", "appointment_date", "time_slot")},
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField(help_text="Doctor's diagnosis")),
                ("symptoms_observed", models.TextField(blank=True, null=True)),
                (
                    "treatment_plan",
                    models.TextField(help_text="Treatment plan and recommendations"),
                ),
                (
                    "medications_prescribed",
                    models.TextField(
                        blank=True,
                        help_text="List of prescribed medications",
                        null=True,
                    ),
                ),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True, null=True)),
                (
                    "doctor_notes",
                    models.TextField(
                        blank=True, help_text="Additional doctor notes", null=True
                    ),
                ),
                (
                    "vital_signs",
                    models.JSONField(
                        blank=True, default=dict, help_text="Vital signs as JSON"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "db_table": "appointments_medical_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "wait_time_rating",
                    models.IntegerField(
                        help_text="Wait time rating from 1 to 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "doctor_care_rating",
                    models.IntegerField(
                        help_text="Doctor care rating from 1 to 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "staff_courtesy_rating",
                    models.IntegerField(
                        help_text="Staff courtesy rating from 1 to 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("would_recommend", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_review",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Review",
                "verbose_name_plural": "Appointment Reviews",
                "db_table": "appointments_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentReschedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_date", models.DateField()),
                ("new_date", models.DateField()),
                ("reason", models.TextField(help_text="Reason for rescheduling")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reschedule_requests",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reschedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_reschedules",
                        to="doctors.timeslot",
                    ),
                ),
                (
                    "original_time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_reschedules",
                        to="doctors.timeslot",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reschedule_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Reschedule",
                "verbose_name_plural": "Appointment Reschedules",
                "db_table": "appointments_reschedule",
                "ordering": ["-created_at"],
            },
        ),
    ]
