# Generated by Django 4.2.7 on 2026-04-29 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_BOOKED", "Appointment Booked"),
                            ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                            ("APPOINTMENT_CONFIRMED", "Appointment Confirmed"),
                            ("APPOINTMENT_RESCHEDULED", "Appointment Rescheduled"),
                            ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("MEDICAL_RECORD_UPDATED", "Medical Record Updated"),
                            ("DOCTOR_AVAILABLE", "Doctor Available"),
                            ("SYSTEM_ANNOUNCEMENT", "System Announcement"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Template for notification title. Use {variable} placeholders",
                        max_length=200,
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Template for notification message. Use {variable} placeholders"
                    ),
                ),
                (
                    "action_url_template",
                    models.URLField(
                        blank=True,
                        help_text="Template for action URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "action_text_template",
                    models.CharField(
                        blank=True,
                        help_text="Template for action text",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("default_is_important", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notifications_template",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_appointment_booked", models.BooleanField(default=True)),
                ("email_appointment_cancelled", models.BooleanField(default=True)),
                ("email_appointment_confirmed", models.BooleanField(default=True)),
                ("email_appointment_rescheduled", models.BooleanField(default=True)),
                ("email_appointment_reminder", models.BooleanField(default=True)),
                ("email_payment_received", models.BooleanField(default=True)),
                ("email_payment_failed", models.BooleanField(default=True)),
                ("email_medical_record_updated", models.BooleanField(default=True)),
                ("email_doctor_available", models.BooleanField(default=True)),
                ("email_system_announcements", models.BooleanField(default=True)),
                ("push_appointment_booked", models.BooleanField(default=True)),
                ("push_appointment_cancelled", models.BooleanField(default=True)),
                ("push_appointment_confirmed", models.BooleanField(default=True)),
                ("push_appointment_rescheduled", models.BooleanField(default=True)),
                ("push_appointment_reminder", models.BooleanField(default=True)),
                ("push_payment_received", models.BooleanField(default=True)),
                ("push_payment_failed", models.BooleanField(default=True)),
                ("push_medical_record_updated", models.BooleanField(default=True)),
                ("push_doctor_available", models.BooleanField(default=True)),
                ("push_system_announcements", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(default="22:00:00")),
                ("quiet_hours_end", models.TimeField(default="08:00:00")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notifications_preference",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_BOOKED", "Appointment Booked"),
                            ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                            ("APPOINTMENT_CONFIRMED", "Appointment Confirmed"),
                            ("APPOINTMENT_RESCHEDULED", "Appointment Rescheduled"),
                            ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("MEDICAL_RECORD_UPDATED", "Medical Record Updated"),
                            ("DOCTOR_AVAILABLE", "Doctor Available"),
                            ("SYSTEM_ANNOUNCEMENT", "System Announcement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_important", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to redirect when notification is clicked",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True,
                        help_text="Text for action button",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Notification expires at this time",
                        null=True,
                    ),
                ),
                (
                    "related_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "related_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="doctors.doctorprofile",
                    ),
                ),
                (
                    "related_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="notificatio_user_id_8a7c6b_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_f2e0f7_idx",
                    ),
                    models.Index(
                        fields=["priority", "is_read"],
                        name="notificatio_priorit_60753b_idx",
                    ),
                ],
            },
        ),
    ]
